export const CAPTURE_GUIDE_FRAME_HEIGHT = 320;
export const CAPTURE_GUIDE_CIRCLE_DIAMETER = 190;

export const CAPTURE_GUIDE_RADIUS_RATIO =
  CAPTURE_GUIDE_CIRCLE_DIAMETER / (2 * CAPTURE_GUIDE_FRAME_HEIGHT);
